### ISSUE TITLE
TableView cells seems to reload of it has gone out of view.

### ISSUE THREAD

**Issue by Sweeper777** [tbergmen/TableViewModel#1]
I created a tableview controller  with TableViewModel. My cells contain `UITextField`s. When I scroll the tableview and the cells go out of view i.e. I can't see them anymore, the text fields in them seem to reset.

To clarify, say I wrote something in the text field and scroll down until I can't see the cell with the text field. When I scroll back up, the text fields appear to be empty.

This only happens sometimes though, so you may need to try a few times to reproduce.

This is my code: https://github.com/Sweeper777/MathToolbox-Free/blob/b0f58c481ad2ef2efa356e3eb23bdc5a13735a56/MathToolbox/CustOpEditorController.swift

I think only line 26 - line 175 is relevant.

**Comment by tbergmen** [comment]
Hello. This is happening because the cells are queued and reused each time they are displayed. You need to override prepareForReuse() method of UITableViewCell and reset the text field value to the correct one.
