### ISSUE TITLE
Ability to disable row selection. 

### ISSUE THREAD

**Issue by markst** [tbergmen/TableViewModel#5]
The same way it's possible to deselect rows after selection, it would be good to be able to enable/disable selection of certain rows.

**Comment by tbergmen** [comment]
Thank you for the pull request. It is now merged.

**Comment by markst** [comment]
@tbergmen no worries. Though I think I might create another PR and update to use `shouldHighlightRowAtIndexPath` delegate rather than `willSelectRowAtIndexPath`. So that the state of the `UITableViewCell` is not highlighted at all...
